layout of the first two pages
htmlacademy-htmlcss/826593-device-32 pull request #2
Opened 2021-10-05 04:56 UTC by SosninVitaliy

100% не идеально, времени в обрез( Буду на стилях подгонять макет

2021-10-05 08:10 UTC, davletbaev requested changes
Привет! Довольно неплохо получилось с первой попытки)
Осталось немного доработать, прежде чем приступать к стилизации

2021-10-05 08:10 UTC, davletbaev commented on index.html
> +        <ul class="services-list">
Зачем здесь по отдельному списку на каждый блок?
Их можно просто все в один див поместить, даже без списка, потому что они будут отображаться по одному за раз, а не все вместе.

2021-10-05 08:10 UTC, davletbaev commented on index.html
> +        <h2 class="visually-hidden">Доставка под заказ</h2>
Это тоже не раздел сайта, а скорее рекламный баннер.
Так что сюда не стоит делать отдельный заголовок, к тому же он у тебя дублирует сам текст баннера.
Кроме того, этот баннер раскрывает модальное окно с формой оформления доставки (есть в макете), так что здесь будет кнопка, а не ссылка.

2021-10-05 08:10 UTC, davletbaev commented on index.html
> +      <a class="logo-logo" href="#">
Странное название класса)
Лучше таких не использовать, потому что потом сам в них запутаешься. 
Лучше здесь просто оставить logo, а картинке дать класс logo-image

2021-10-06 12:33 UTC, davletbaev requested changes
Привет, не вижу исправлений по многим комментариям. 
Особенно по слайдеру, в котором у тебя должны быть сверстаны все слайды.
Пожалуйста, перечитай все оставшиеся комментарии.

2021-10-06 17:29 UTC, SosninVitaliy reviewed
+

2021-10-08 00:34 UTC, davletbaev requested changes
Привет, уже лучше, но есть еще комментарии, которые надо доработать.
Особенно обрати внимание на формы.
Поправишь эти моменты и я приму задание.

2021-10-08 00:34 UTC, davletbaev commented on catalog.html
> +        <label class="visually-hidden" for="search-input"></label>
Не понятно, зачем здесь этот спрятанный пустой label)

2021-10-08 00:34 UTC, davletbaev commented on catalog.html
> +        <label class="visually-hidden" for="search-input"></label>
К тому же лучше этот блок все-таки тоже должен находится внутри nav, так как относится к навигации.

2021-10-08 00:34 UTC, davletbaev commented on catalog.html
> +        </aside>
В aside должен быть не только заголовок, а вообще весь фильтр :)

2021-10-08 00:34 UTC, davletbaev commented on catalog.html
> +        <aside class="pagination-block">
А вот пагинация это уже не aside. Сюда логичнее будет использовать nav, или оставить div, как было.

2021-10-08 00:34 UTC, davletbaev commented on catalog.html
> +          <p class="catalog-products-title">фильтр:</p>
зачем заменил заголовок на абзац? заголовок сюда больше подходит, только скорее h3. То же самое в сортировке.

2021-10-08 00:34 UTC, davletbaev commented on catalog.html
>            <label class="visually-hidden" for="sorting">Сортировка</label>
Этот label дублирует текст заголовка, лучше его убрать.

2021-10-08 00:34 UTC, davletbaev commented on catalog.html
>            <label class="visually-hidden" for="sorting">Сортировка</label>
По поводу самой сортировки, у тебя там 3 кнопки с типом visually-hidden и типом submit.
1) одна кнопка "отсортировать продукты" лишняя. Форма будет работать через js, а если ты разместил кнопку сюда на случай отключения js (что в принципе похвально), то надо поместить ее в тег noscript. Тогда кнопка будет отображаться только при отключенном js и без класса visually-hidden. И не забудь к форме нужные атрибуты добавить, которые написаны в ТЗ. 
2) две другие кнопки - это не кнопки, это радио-боксы. Так как их можно выбрать, и в каждый момент времени может быть выбран только один.

2021-10-10 12:18 UTC, davletbaev requested changes
Поправь последние 2 комментария, отправлять на повторную проверку не нужно, я приму так.

2021-10-10 12:18 UTC, davletbaev commented on catalog.html
> +              <button class="range-toggle toggle-min" type="button">
В прошлый раз не заметил этих кнопок, их тут не должно быть, разметки в блоке с классом range достаточно

2021-10-10 12:18 UTC, davletbaev commented on catalog.html
> +          <input class="visually-hidden button-up" type="radio" name="button-arrow" value="up">
Тут тебе нужен label через который ты их будешь стилизовать. 
В качестве name здесь подойдет sort-direction, а value  —  ascending/descending

2021-10-10 12:41 UTC, merged