done graphics for all pages
htmlacademy-htmlcss/826593-device-32 pull request #3
Opened 2021-10-10 22:54 UTC by SosninVitaliy

Экспортировал изображения в папку img. Подключил контентные изображения, декоративные не подключал, так как нету фоновых и текстур.

2021-10-14 10:43 UTC, davletbaev commented on css/styles.css
> +  font-family: "raleway", sans-serif;;
Опечатка, лишняя точка с запятой

2021-10-14 10:51 UTC, davletbaev commented on index.html
> +          <p class="gallery-number">01</p>
это лучше реализовать через псевдоэлемент

2021-10-14 10:52 UTC, davletbaev commented on index.html
> +                <svg width="86" height="117" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M82.821 4.011H3.33C1.569 4.011.141998 5.438.141998 7.199v46.413c0 1.763 1.427002 3.189 3.188002 3.
Я думал ты целиком квадратик вставишь как svg, тогда мог бы у него фон менять. 
А вставлять просто иконку через svg смысла нет. Лучше использовать img для этого, чтобы не засорять разметку.

2021-10-14 10:55 UTC, davletbaev commented on index.html
> +                <svg width="86" height="117" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M82.821 4.011H3.33C1.569 4.011.141998 5.438.141998 7.199v46.413c0 1.763 1.427002 3.189 3.188002 3.
И если собираешься активно использовать svg в работе, тогда лучше делать это через спрайт
https://snipp.ru/html-css/svg-sprite
Если хочешь, то могу подробнее рассказать об этом на консультации.

2021-10-17 10:51 UTC, merged

2021-10-17 10:51 UTC, davletbaev requested changes

2021-10-17 10:51 UTC, davletbaev commented on index.html
> +            <a class="product-categories-link-item" href="#">
С картинками все ок, но по реализации самих карточек лучше будет сделать не 2 отдельные ссылки, а обернуть все содержимое карточек в одну ссылку. Тогда все содержимое станет ссылками. Главное не менять display у ссылки. А если потребуется flex или grid, то использовать дополнительный div внутри.

2021-10-17 10:51 UTC, davletbaev commented on css/styles.css
> +  content: "01";
Такое решение тоже пойдет, но имеет свои ограничения. Например, если слайдов будет больше 3, то все сломается, и тебе придется дописывать стили. 
Почитай про css-счетчики https://developer.mozilla.org/ru/docs/Web/CSS/CSS_Lists_and_Counters/Using_CSS_counters

2021-10-18 17:29 UTC, SosninVitaliy commented on index.html
> +            <a class="product-categories-link-item" href="#">
Если делать общей ссылкой, то между картинкой и текстом ссылочное пространство получается